directories:
  upload_files_sqldb_dir: data\uploaded_files_sqldb.db
  upload_files_dir: data\uploaded_files.db
  sqldb_directory: data\sqldb.db
  persist_directory: data\chroma

llm_config:
  agent_llm_system_role: "Given the following user question, corresponding SQL query, and SQL result, answer the user question.\n
    Question: {question}\n
    SQL Query: {query}\n
    SQL Result: {result}\n
    Answer: 
    "
  llm_system_role: "Given the following user question, answer the user question.\n"
  temperature: 0.0
  